In [ ]:
# https://github.com/mjtaheri11/FL-wireless/blob/main/train.py
# https://github.com/mmd-yousefi/Federate-Learning-on-Wireless-networks/blob/main/FL_Over_Wireless.ipynb
# A Joint Learning and Communications Framework for Federated Learning Over Wireless Networks

In [ ]:
import numpy as np

In [ ]:
RBnumber = 10
np.random.seed(1)
i = np.array([0.05 + i * 0.01 for i in range(RBnumber)])
user_I = (i-0.04)*0.000001
print(i)
print(user_I)

[0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14]
[1.e-08 2.e-08 3.e-08 4.e-08 5.e-08 6.e-08 7.e-08 8.e-08 9.e-08 1.e-07]


In [ ]:
total_model_params = 101770

# (np.inf indica um canal sem perda de pacotes) ou (delay e energy não são limitados)
delay_req=np.inf
energy_req=np.inf

# delay_req=0.2
# energy_req=0.0025

user_P = 0.01
user_Bw = 1 # MHz

In [ ]:
usernumber = 100

np.random.seed(1)
a, b = 100, 500
d, angles = a + (b - a) * np.random.rand(usernumber,1), 2 * np.pi * np.random.rand(usernumber)
np.random.seed()
for i in d:
  print(i)

[266.80880188]
[388.12979738]
[100.04574993]
[220.93302905]
[158.70235633]
[136.93543791]
[174.50408455]
[238.22429082]
[258.70698969]
[315.5266936]
[267.67780576]
[374.08780016]
[181.78089989]
[451.24697456]
[110.95503728]
[368.18700407]
[266.92192095]
[323.47593138]
[156.15477544]
[179.24059563]
[420.29782747]
[487.30463029]
[225.36967126]
[376.92904627]
[450.55566092]
[457.8426654]
[134.01768455]
[115.62191329]
[167.93216783]
[451.25700137]
[139.33873353]
[268.44305]
[483.15581206]
[313.26611399]
[376.75084558]
[226.2062524]
[374.60037107]
[433.85026876]
[107.31531094]
[400.05772598]
[495.54443556]
[399.26626175]
[212.17759683]
[415.71173138]
[141.29040263]
[279.15741047]
[463.43820124]
[217.44565935]
[215.11013543]
[152.01142885]
[107.74678315]
[371.53421318]
[184.6512464]
[206.21866375]
[296.62926371]
[121.34501805]
[329.6470422]
[158.69142996]
[335.72221476]
[379.90334401]
[140.93377153]
[265.62239513]
[377.76006309]
[265.67170781]
[119.98138358]
[314.35856237]
[365.51785809]
[30

In [ ]:
N  = 10**-20
q = 1 - np.exp(-1.08 * (user_I + N*user_Bw) / (user_P * (d**-2))) # Packet error rate of each user over each RB
# q

array([[0.07400078, 0.14252545, 0.20597924, 0.2647374 , 0.31914741,
        0.36953104, 0.41618623, 0.45938891, 0.49939456, 0.53643975],
       [0.15015077, 0.27775628, 0.38620173, 0.47836401, 0.55668806,
        0.62325168, 0.67982073, 0.7278959 , 0.76875254, 0.80347452],
       [0.01075167, 0.02138774, 0.03190945, 0.04231804, 0.05261472,
        0.06280069, 0.07287714, 0.08284526, 0.0927062 , 0.10246112],
       [0.05135091, 0.1000649 , 0.14627739, 0.19011682, 0.23170506,
        0.2711577 , 0.30858441, 0.34408923, 0.37777085, 0.40972288],
       [0.02683473, 0.05294935, 0.0783632 , 0.10309507, 0.12716327,
        0.15058561, 0.17337941, 0.19556155, 0.21714844, 0.23815605],
       [0.02004774, 0.03969356, 0.05894553, 0.07781154, 0.09629934,
        0.11441649, 0.13217043, 0.14956845, 0.16661768, 0.18332511],
       [0.03235289, 0.06365906, 0.09395239, 0.12326565, 0.15163053,
        0.17907774, 0.20563694, 0.23133688, 0.25620535, 0.28026925],
       [0.05945038, 0.11536642, 0.1679582

In [ ]:
bs_P = 1 # W
o = 1 # Rayleigh fading parameter
h = o * (d ** (-2))
user_SINR = user_P * h / (user_I + user_Bw*N)
user_SINR

array([[14.04752115,  7.02376058,  4.68250705,  3.51188029,  2.80950423,
         2.34125353,  2.00678874,  1.75594014,  1.56083568,  1.40475212],
       [ 6.63813421,  3.31906711,  2.2127114 ,  1.65953355,  1.32762684,
         1.1063557 ,  0.94830489,  0.82976678,  0.73757047,  0.66381342],
       [99.9085629 , 49.95428145, 33.3028543 , 24.97714072, 19.98171258,
        16.65142715, 14.27265184, 12.48857036, 11.10095143,  9.99085629],
       [20.48701598, 10.24350799,  6.82900533,  5.121754  ,  4.0974032 ,
         3.41450266,  2.92671657,  2.560877  ,  2.27633511,  2.0487016 ],
       [39.70390747, 19.85195373, 13.23463582,  9.92597687,  7.94078149,
         6.61731791,  5.67198678,  4.96298843,  4.41154527,  3.97039075],
       [53.32959555, 26.66479778, 17.77653185, 13.33239889, 10.66591911,
         8.88826593,  7.61851365,  6.66619944,  5.92551062,  5.33295956],
       [32.83891552, 16.41945776, 10.94630517,  8.20972888,  6.5677831 ,
         5.47315259,  4.69127365,  4.10486444

In [ ]:
for i in d:
  print(i)

[266.80880188]
[388.12979738]
[100.04574993]
[220.93302905]
[158.70235633]
[136.93543791]
[174.50408455]
[238.22429082]
[258.70698969]
[315.5266936]
[267.67780576]
[374.08780016]
[181.78089989]
[451.24697456]
[110.95503728]
[368.18700407]
[266.92192095]
[323.47593138]
[156.15477544]
[179.24059563]
[420.29782747]
[487.30463029]
[225.36967126]
[376.92904627]
[450.55566092]
[457.8426654]
[134.01768455]
[115.62191329]
[167.93216783]
[451.25700137]
[139.33873353]
[268.44305]
[483.15581206]
[313.26611399]
[376.75084558]
[226.2062524]
[374.60037107]
[433.85026876]
[107.31531094]
[400.05772598]
[495.54443556]
[399.26626175]
[212.17759683]
[415.71173138]
[141.29040263]
[279.15741047]
[463.43820124]
[217.44565935]
[215.11013543]
[152.01142885]
[107.74678315]
[371.53421318]
[184.6512464]
[206.21866375]
[296.62926371]
[121.34501805]
[329.6470422]
[158.69142996]
[335.72221476]
[379.90334401]
[140.93377153]
[265.62239513]
[377.76006309]
[265.67170781]
[119.98138358]
[314.35856237]
[365.51785809]
[30

In [ ]:
user_rate = user_Bw * np.log2(1 + user_SINR) # user_Bw com 1MHz
user_rate

array([[3.91145394, 3.00427856, 2.50652757, 2.17372879, 1.92960326,
        1.74038945, 1.5882235 , 1.46254455, 1.35661469, 1.26588819],
       [2.93322027, 2.11071973, 1.68379139, 1.41117324, 1.21885979,
        1.07474909, 0.96221946, 0.87165977, 0.79707149, 0.73449366],
       [6.65690479, 5.67113147, 5.10025672, 4.69917074, 4.39106053,
        4.14171293, 3.93287868, 3.75366554, 3.59704858, 3.45823188],
       [4.42539324, 3.49102032, 2.96882903, 2.61394507, 2.34976247,
        2.14225091, 1.97332347, 1.8322326 , 1.71208293, 1.60819495],
       [5.34709539, 4.38211066, 3.83133368, 3.44969037, 3.16040094,
        2.92928311, 2.73811643, 2.57603554, 2.43604062, 2.31335927],
       [5.7636664 , 4.78997947, 4.23085871, 3.8412082 , 3.54422807,
        3.30571754, 3.10743908, 2.93851153, 2.79192044, 2.66287987],
       [5.08061143, 4.12262781, 3.57849258, 3.20315869, 2.91987074,
        2.69446851, 2.50875155, 2.35187265, 2.21684855, 2.09892196],
       [4.21885036, 3.2943188 , 2.7810724

In [ ]:
bs_I = 0.06*0.000003;  # Interference over downlink
bs_Bw = 20  # MHz
bs_SINR = bs_P * h / (bs_I + N*bs_Bw)
bs_SINR

array([[ 78.04178419],
       [ 36.8785234 ],
       [555.04757166],
       [113.81675545],
       [220.57726372],
       [296.27553086],
       [182.43841955],
       [ 97.89385011],
       [ 83.00632182],
       [ 55.80270889],
       [ 77.53588846],
       [ 39.69907655],
       [168.12449654],
       [ 27.28342503],
       [451.2668667 ],
       [ 40.98175802],
       [ 77.97565141],
       [ 53.09376838],
       [227.83317095],
       [172.92378703],
       [ 31.44946085],
       [ 23.39518151],
       [109.37965582],
       [ 39.10283845],
       [ 27.36721434],
       [ 26.50299609],
       [309.31663318],
       [415.57287366],
       [196.99704255],
       [ 27.28221258],
       [286.14342897],
       [ 77.09445911],
       [ 23.79869145],
       [ 56.61097769],
       [ 39.13983797],
       [108.57211183],
       [ 39.59050928],
       [ 29.51533747],
       [482.39646698],
       [ 34.71220252],
       [ 22.62362988],
       [ 34.8499587 ],
       [123.40377423],
       [ 32

In [ ]:
bs_rate = bs_Bw * np.log2(1 + bs_SINR)
bs_rate

array([[126.09087215],
       [104.86616374],
       [182.3812901 ],
       [136.86378765],
       [155.83332084],
       [164.31313816],
       [150.3830404 ],
       [132.55617804],
       [127.84851991],
       [116.55775655],
       [125.90560333],
       [106.93848311],
       [148.03883659],
       [ 96.43769862],
       [176.42060994],
       [107.83381354],
       [126.06672053],
       [115.14780999],
       [156.76304771],
       [148.84622898],
       [100.40245206],
       [ 92.17048624],
       [135.72660964],
       [106.51264896],
       [ 96.52305159],
       [ 95.63033769],
       [165.55194436],
       [174.04850174],
       [152.58670142],
       [ 96.43646169],
       [163.31255474],
       [125.74296572],
       [ 92.64384183],
       [116.96543673],
       [106.53925776],
       [135.51473683],
       [106.86141072],
       [ 98.62925281],
       [178.34126237],
       [103.16690417],
       [ 91.24317507],
       [103.27799103],
       [139.1777289 ],
       [101

In [ ]:
print(total_model_params)

101770


In [ ]:
# numpy.float32, cada parâmetro tem 4 bytes
Z=total_model_params*4  / (1024 ** 2) # MBytes
Z

0.38822174072265625

In [ ]:
user_delay = Z / user_rate
user_delay

array([[0.09925254, 0.12922295, 0.15488429, 0.17859714, 0.20119252,
        0.22306602, 0.24443773, 0.26544268, 0.2861695 , 0.30667933],
       [0.13235342, 0.18392861, 0.23056404, 0.27510566, 0.31851222,
        0.36122081, 0.40346486, 0.44538219, 0.48706013, 0.52855697],
       [0.05831866, 0.06845578, 0.07611808, 0.08261495, 0.08841184,
        0.09373458, 0.09871185, 0.1034247 , 0.10792786, 0.11226018],
       [0.08772593, 0.11120581, 0.13076595, 0.14851947, 0.16521744,
        0.18122141, 0.19673497, 0.21188453, 0.22675405, 0.24140216],
       [0.07260423, 0.08859241, 0.10132809, 0.11253814, 0.1228394 ,
        0.13253131, 0.14178423, 0.15070512, 0.15936587, 0.16781731],
       [0.06735673, 0.08104873, 0.09175956, 0.10106761, 0.10953633,
        0.11743948, 0.12493302, 0.1321151 , 0.13905186, 0.14579018],
       [0.07641241, 0.09416852, 0.10848751, 0.12119966, 0.13295854,
        0.14408101, 0.15474699, 0.1650692 , 0.17512326, 0.18496245],
       [0.09202074, 0.11784583, 0.1395942

In [ ]:
bs_delay = Z / bs_rate
bs_delay

array([[0.0030789 ],
       [0.00370207],
       [0.00212863],
       [0.00283656],
       [0.00249126],
       [0.00236269],
       [0.00258155],
       [0.00292873],
       [0.00303658],
       [0.00333072],
       [0.00308343],
       [0.00363033],
       [0.00262243],
       [0.00402562],
       [0.00220055],
       [0.00360019],
       [0.00307949],
       [0.00337151],
       [0.00247649],
       [0.00260821],
       [0.00386666],
       [0.004212  ],
       [0.00286032],
       [0.00364484],
       [0.00402206],
       [0.00405961],
       [0.00234501],
       [0.00223054],
       [0.00254427],
       [0.00402567],
       [0.00237717],
       [0.00308742],
       [0.00419048],
       [0.00331912],
       [0.00364393],
       [0.00286479],
       [0.00363295],
       [0.00393617],
       [0.00217685],
       [0.00376305],
       [0.0042548 ],
       [0.003759  ],
       [0.0027894 ],
       [0.00384316],
       [0.00238887],
       [0.00314313],
       [0.00408848],
       [0.002

In [ ]:
totaldelay = user_delay + bs_delay
totaldelay

array([[0.10233144, 0.13230186, 0.15796319, 0.18167604, 0.20427142,
        0.22614492, 0.24751663, 0.26852158, 0.2892484 , 0.30975823],
       [0.13605549, 0.18763068, 0.23426611, 0.27880773, 0.32221429,
        0.36492288, 0.40716693, 0.44908426, 0.4907622 , 0.53225904],
       [0.06044728, 0.07058441, 0.07824671, 0.08474357, 0.09054047,
        0.09586321, 0.10084048, 0.10555333, 0.11005648, 0.11438881],
       [0.09056249, 0.11404236, 0.1336025 , 0.15135603, 0.168054  ,
        0.18405797, 0.19957153, 0.21472108, 0.22959061, 0.24423872],
       [0.07509549, 0.09108367, 0.10381936, 0.1150294 , 0.12533066,
        0.13502258, 0.1442755 , 0.15319638, 0.16185714, 0.17030858],
       [0.06971943, 0.08341142, 0.09412226, 0.10343031, 0.11189903,
        0.11980217, 0.12729571, 0.13447779, 0.14141456, 0.14815288],
       [0.07899396, 0.09675007, 0.11106906, 0.12378121, 0.13554009,
        0.14666256, 0.15732854, 0.16765075, 0.17770481, 0.187544  ],
       [0.09494948, 0.12077457, 0.1425229

In [ ]:
energy_coeff = 10 ** (-27)
cpu_cycles = 40
cpu_freq = 10 ** 9

In [ ]:
user_energy_training = energy_coeff * cpu_cycles * (cpu_freq ** 2) * Z
user_energy_training

1.552886962890625e-08

In [ ]:
user_upload_energy = user_P * user_delay
user_upload_energy

array([[0.00099253, 0.00129223, 0.00154884, 0.00178597, 0.00201193,
        0.00223066, 0.00244438, 0.00265443, 0.00286169, 0.00306679],
       [0.00132353, 0.00183929, 0.00230564, 0.00275106, 0.00318512,
        0.00361221, 0.00403465, 0.00445382, 0.0048706 , 0.00528557],
       [0.00058319, 0.00068456, 0.00076118, 0.00082615, 0.00088412,
        0.00093735, 0.00098712, 0.00103425, 0.00107928, 0.0011226 ],
       [0.00087726, 0.00111206, 0.00130766, 0.00148519, 0.00165217,
        0.00181221, 0.00196735, 0.00211885, 0.00226754, 0.00241402],
       [0.00072604, 0.00088592, 0.00101328, 0.00112538, 0.00122839,
        0.00132531, 0.00141784, 0.00150705, 0.00159366, 0.00167817],
       [0.00067357, 0.00081049, 0.0009176 , 0.00101068, 0.00109536,
        0.00117439, 0.00124933, 0.00132115, 0.00139052, 0.0014579 ],
       [0.00076412, 0.00094169, 0.00108488, 0.001212  , 0.00132959,
        0.00144081, 0.00154747, 0.00165069, 0.00175123, 0.00184962],
       [0.00092021, 0.00117846, 0.0013959

In [ ]:
total_energy = user_energy_training + user_upload_energy
total_energy

array([[0.00099254, 0.00129225, 0.00154886, 0.00178599, 0.00201194,
        0.00223068, 0.00244439, 0.00265444, 0.00286171, 0.00306681],
       [0.00132355, 0.0018393 , 0.00230566, 0.00275107, 0.00318514,
        0.00361222, 0.00403466, 0.00445384, 0.00487062, 0.00528559],
       [0.0005832 , 0.00068457, 0.0007612 , 0.00082616, 0.00088413,
        0.00093736, 0.00098713, 0.00103426, 0.00107929, 0.00112262],
       [0.00087727, 0.00111207, 0.00130768, 0.00148521, 0.00165219,
        0.00181223, 0.00196737, 0.00211886, 0.00226756, 0.00241404],
       [0.00072606, 0.00088594, 0.0010133 , 0.0011254 , 0.00122841,
        0.00132533, 0.00141786, 0.00150707, 0.00159367, 0.00167819],
       [0.00067358, 0.0008105 , 0.00091761, 0.00101069, 0.00109538,
        0.00117441, 0.00124935, 0.00132117, 0.00139053, 0.00145792],
       [0.00076414, 0.0009417 , 0.00108489, 0.00121201, 0.0013296 ,
        0.00144083, 0.00154749, 0.00165071, 0.00175125, 0.00184964],
       [0.00092022, 0.00117847, 0.0013959

In [ ]:
# A simulação para cada rodada de comunicação começa aqui

In [ ]:
def selecao_clientes_aleatoria(): # cada rodada seleciona 10 clientes de 100
  np.random.seed(1) # Na simulação para cada rodada de comunicação -> não utilizar seed()
  assignment = np.zeros(usernumber, dtype=int)

  if RBnumber < usernumber:
    assignment[np.random.permutation(usernumber)[:RBnumber]] = 1
  else:
      assignment[:] = 1

  selected_clients = np.where(assignment > 0)[0]

  return assignment, selected_clients

assignment, selected_clients = selecao_clientes_aleatoria()
assignment, selected_clients

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([17, 33, 36, 65, 69, 80, 81, 82, 84, 93]))

In [ ]:
def atribuicao_RBs_aleatoria(assignment):
  np.random.seed(1) # Na simulação para cada rodada de comunicação -> não utilizar seed()
  qassignment = np.zeros(usernumber, dtype=int)

  qassignment[np.where(assignment > 0)] = np.random.permutation(RBnumber)[:usernumber] = 1
  rb_allocation = np.random.permutation(np.where(qassignment > 0)[0])

  return qassignment, rb_allocation

qassignment, rb_allocation = atribuicao_RBs_aleatoria(assignment)
qassignment, selected_clients, rb_allocation, d[selected_clients]

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([17, 33, 36, 65, 69, 80, 81, 82, 84, 93]),
 array([93, 80, 65, 17, 84, 69, 36, 33, 81, 82]),
 array([[323.47593138],
        [313.26611399],
        [374.60037107],
        [314.35856237],
        [334.6220162 ],
        [453.32243648],
        [349.46888282],
        [400.37697361],
        [207.97115671],
        [331.35584575]]))

In [ ]:
def atribuicao_RBs(selected_clients): # usar essa heurística
  qassignment = np.zeros(usernumber, dtype=int)

  combined_data = list(zip(d[selected_clients], np.arange(len(selected_clients))))
  sorted_data = sorted(combined_data, reverse=True, key=lambda x: x[0])
  rb_allocation, pos_list = zip(*sorted_data)

  qassignment[selected_clients[np.array(pos_list)]] = 1
  return qassignment, selected_clients[np.array(pos_list)]

In [ ]:
qassignment, rb_allocation = atribuicao_RBs(selected_clients)
qassignment, selected_clients, rb_allocation, d[selected_clients]

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([17, 33, 36, 65, 69, 80, 81, 82, 84, 93]),
 array([80, 82, 36, 81, 69, 93, 17, 65, 33, 84]),
 array([[323.47593138],
        [313.26611399],
        [374.60037107],
        [314.35856237],
        [334.6220162 ],
        [453.32243648],
        [349.46888282],
        [400.37697361],
        [207.97115671],
        [331.35584575]]))

In [ ]:
# Quando o dispositivo decidir não trasmitir, compute user_energy_training e não inclua user_upload_energy
final_total_energy = 0
for i in range(len(selected_clients)):
  iclient = selected_clients[i]
  irb = rb_allocation.tolist().index(iclient)
  final_total_energy = final_total_energy + user_energy_training + user_upload_energy[iclient, irb]
  print(f"{i}: -> Disp: {selected_clients[i]}, RB: {irb}: {total_energy[iclient, irb]}")
final_total_energy

0: -> Disp: 17, RB: 6: 0.003125784723687222
1: -> Disp: 33, RB: 8: 0.003554001051019016
2: -> Disp: 36, RB: 2: 0.0022120150526334717
3: -> Disp: 65, RB: 7: 0.0032915551263242686
4: -> Disp: 69, RB: 4: 0.002626188475433397
5: -> Disp: 80, RB: 0: 0.001521013741756145
6: -> Disp: 81, RB: 3: 0.002415229568558646
7: -> Disp: 82, RB: 1: 0.001900887066750874
8: -> Disp: 84, RB: 9: 0.0022470377944743096
9: -> Disp: 93, RB: 5: 0.002914038229799632


0.02580775083043698

In [ ]:
0.003125784723687222 + 0.003554001051019016 + 0.0022120150526334717 + 0.0032915551263242686 + 0.002626188475433397 + 0.001521013741756145 + 0.002415229568558646 + 0.001900887066750874 + 0.0022470377944743096 + 0.002914038229799632

0.02580775083043698